server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 'Delivery@1234'
        platform: mysql
        url: jdbc:mysql://localhost/delivery?allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&useTimezone=true&serverTimezone=UTC
        username: delivery
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: create
        show-sql: true
        properties.hibernate:        
            format_sql: true
              
authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
